source "https://supermarket.chef.io"

cookbook "apt"
cookbook "git"
cookbook "vsftpd", git: "https://github.com/TheSerapher/chef-vsftpd.git"
cookbook "nginx"
cookbook "php"
cookbook "php-fpm"
cookbook "mariadb"
cookbook "phing"
cookbook "composer", git: "https://github.com/escapestudios-cookbooks/composer.git"
cookbook "drush", git: "https://github.com/msonnabaum/chef-drush.git"
cookbook "drush-wrap", path: "cookbooks/drush-wrap"
cookbook "phpapp", path: "cookbooks/phpapp"