source "https://supermarket.chef.io"

cookbook "apt"
cookbook "git"
cookbook "vsftpd", git: "https://github.com/TheSerapher/chef-vsftpd.git"
cookbook "nginx"
cookbook "php"
cookbook "php-fpm"
cookbook "mariadb"
cookbook "phing"
cookbook "composer", git: "https://github.com/escapestudios-cookbooks/composer.git"
cookbook "drush", git: "https://github.com/msonnabaum/chef-drush.git"
cookbook "php-fpm-wrapper", path: "chef/cookbooks/php-fpm-wrapper"
cookbook "drush-wrapper", path: "chef/cookbooks/drush-wrapper"
cookbook "phing-wrapper", path: "chef/cookbooks/phing-wrapper"
cookbook "nginx-wrapper", path: "chef/cookbooks/nginx-wrapper"