source "https://supermarket.chef.io"

cookbook "apt"
cookbook "git"
cookbook "nginx"
cookbook "php5-fpm", git: "https://github.com/stajkowski/php5-fpm.git"
cookbook "mariadb", git: "https://github.com/sinfomicien/mariadb.git"
cookbook "phing"
cookbook "drush", git: "https://github.com/msonnabaum/chef-drush.git"
cookbook "phpapp", path: "cookbooks/phpapp"