name             'testing'
maintainer       'Sergey Sergin (ADCI)'
maintainer_email 'sergey-sergin@kruhak.name'
license          'MIT'
description      'Testing application (role) cookbook'
version          '1.0'

depends 'developer'
depends 'phantomjs'
depends 'jenkins'
depends 'selenium-wrapper'